'use strict';
const D=window.RESEARCH;
const state={scenario:'central',horizon:2,growth:2,newWork:10,weights:{},taskQuery:'',taskTag:'All',sourceQuery:'',sourceKind:'All'};
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>(n*100).toFixed(1)+'%';
const whole=n=>Math.round(n)+'%';
const source=id=>D.sources.find(s=>s.id===id);
const refs=(ids,forecast=false)=>`<div class="citations">${forecast?'Scenario assumptions: <a href="#methods" title="Open A01 model assumptions">[A01]</a> · Research context: ':'Sources: '}${ids.map(id=>`<a href="#references/${id}" title="${esc(source(id)?.title||id)}">[${id}]</a>`).join('')}</div>`;
const badge=(label,type='observed')=>`<span class="badge ${type}">${label}</span>`;
const intro=(label,title,body)=>`<div class="section-intro"><div class="eyebrow">${label}</div><h1>${title}</h1><p class="lead">${body}</p></div>`;
const estimate=(sc,i)=>Forecast.estimate(D,sc,i,state.weights);
function chart(){
 const W=780,H=295,L=44,R=28,T=22,B=37;
 const x=y=>L+(y-2026)/30*(W-L-R),y=v=>T+(1-v)*(H-T-B);
 let svg=`<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="chartTitle chartDesc"><title id="chartTitle">Additional engineering labor hours removed per fixed-scope project, 2026 to 2056</title><desc id="chartDesc">Author assumptions. ${D.scenarios.map(s=>s.name+': '+D.horizons.map((yr,i)=>yr+' '+pct(estimate(s.id,i).net)).join(', ')).join('. ')}. Baseline includes existing 2026 automation. These are not job loss rates.</desc>`;
 for(let v=0;v<=1.001;v+=.25)svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="var(--line)"/><text x="${L-9}" y="${y(v)+4}" fill="var(--muted)" text-anchor="end" font-size="10">${Math.round(v*100)}%</text>`;
 D.horizons.forEach(yr=>svg+=`<text x="${x(yr)}" y="${H-8}" fill="var(--muted)" font-size="10" text-anchor="middle">${yr}</text>`);
 D.scenarios.forEach(s=>{
 const points=D.horizons.map((yr,i)=>[x(yr),y(estimate(s.id,i).net)]);
 svg+=`<polyline points="${points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${s.color}" stroke-width="2.7" stroke-dasharray="6 4"/>`;
 points.forEach(([px,py],i)=>svg+=`<circle cx="${px}" cy="${py}" r="4" fill="${s.color}"><title>${s.name}, ${D.horizons[i]}: ${pct(estimate(s.id,i).net)}</title></circle>`);
 });return svg+'</svg>';
}
function snapshotTable(){return `<div class="table-wrap"><table class="forecast-table"><thead><tr><th>Additional hours removed</th>${D.horizons.slice(1).map(y=>`<th>${y}</th>`).join('')}</tr></thead><tbody>${D.scenarios.map(s=>`<tr><td><strong>${s.name}</strong></td>${D.horizons.slice(1).map((y,i)=>`<td>${pct(estimate(s.id,i+1).net)}</td>`).join('')}</tr>`).join('')}</tbody><caption>Author scenario outputs, not published forecasts or probabilities. Baseline task weights ${Object.keys(state.weights).length?'modified by the user':'assumed'}; fixed scope and quality; additional review/rework deducted. ${refs(['S05','S13','S15','S20'],true)}</caption></table></div>`;}
function overview(){return intro('THE PROFESSION, NOT JUST THE CALCULATIONS','Engineering changes.<br><span class="accent">Responsibility remains contested.</span>','A full-workflow view of AI in structural engineering, from concepts and calculations to BIM, construction and professional judgment. Evidence through 30 September 2026; conditional scenarios to 2056.')+
`<div class="thesis"><span class="eyebrow">MY CENTRAL PREDICTION · INFERENCE</span><h2>The production layer compresses. The role shifts toward intent, uncertainty and verification.</h2><p>AI is likely to cut repetitive digital delivery substantially. Structural engineers could supervise more output and larger scopes. That can shrink teams per project even if demand keeps total employment stable. The harder question is whether firms create enough new work—and preserve enough training—to absorb the capacity released.</p>${refs(['S03','S05','S13','S15','S20','S24'],true)}</div>
<div class="grid four stats"><div class="card">${badge('Official outlook')}<div class="metric">+6<small>%</small></div><div class="stat-label">Civil-engineer job growth</div><div class="stat-note">2025–2035 · broad occupation</div>${refs(['S01'])}</div>
<div class="card">${badge('Controlled benchmark')}<div class="metric">~80<small>%</small></div><div class="stat-label">Design iteration time saved</div><div class="stat-note">Arup/YJK endpoints · one workflow</div>${refs(['S20'])}</div>
<div class="card">${badge('Research prototype')}<div class="metric">32<small>%</small></div><div class="stat-label">BIMgent success rate</div><div class="stat-note">Architectural modeling experiment</div>${refs(['S10'])}</div>
<div class="card">${badge('Synthesized task atlas','inference')}<div class="metric">59</div><div class="stat-label">Task examples in 14 clusters</div><div class="stat-note">Includes BIM, field and commercial work</div>${refs(['S02','S03','S04'])}</div></div>
<div class="card block"><div class="section-head"><div><h2>Three paths to 2056</h2><p>Additional baseline labor hours removed per project · fixed scope and quality</p></div>${badge('Author scenarios','forecast')}</div><figure>${chart()}<div class="legend">${D.scenarios.map(s=>`<span><i style="background:${s.color}"></i>${s.name}</span>`).join('')}</div><figcaption>Figure 1. Conditional task-weighted scenario outputs; dashed lines are visual interpolation between horizons. Not measured automation, probabilities or job-loss estimates. Zero in 2026 means no additional saving relative to that baseline.${refs(['S05','S09','S13','S15','S20'],true)}</figcaption></figure>${snapshotTable()}</div>
<div class="grid two block"><div class="card"><h3>Why a big task saving can become a modest project saving</h3><p>If a workflow occupies 20% of baseline hours and saves 80% of those hours, the whole-project gross saving is 0.20 × 0.80 = 16%. Extra checking reduces the net saving further. These inputs are an illustration, not an engineering time-use observation.</p>${refs(['S20'],true)}</div><div class="card"><h3>Why fewer hours need not mean fewer engineers</h3><p>More projects, deeper assessments, additional alternatives or new assurance work can absorb capacity. Unfunded infrastructure need alone cannot do that. The scenario lab lets demand and new work vary instead of equating automation with unemployment.</p>${refs(['S01','S19','S24'],true)}</div></div>
<div class="notice"><strong>Evidence boundary.</strong> This selected review found no representative study measuring AI’s effect on the complete structural-engineering workload. Percentages beyond observed source results are transparent assumptions. No confidence intervals or scenario probabilities are implied. <a href="#methods">Read the method.</a></div>
<div class="button-row"><a href="#scenarios">Explore the scenario lab →</a><a href="#tasks">Inspect every task</a><a href="#references">Audit the references</a></div>`;}
function timeline(){return intro('2026 → 2056','A timeline with<br><span class="accent">more than one ending.</span>','The nearer-term direction is more defensible than the pace. After 2036, treat these as contingent futures rather than scheduled milestones.')+`<div class="notice">All future descriptions below are author inferences anchored to the linked evidence. Only the 2026 row describes current research and documented deployments. <a href="#methods">A01 assumptions</a>.</div><div class="timeline">${D.timeline.map((t,i)=>`<article class="timeline-row"><div class="year">${t.year}<small>${t.label}</small></div><div class="card"><div class="confidence">${t.confidence}</div><h2>${t.title}</h2><p>${t.body}</p><div class="timeline-details"><div><h4>BIM and documentation</h4><p>${t.bim}</p></div><div><h4>People and firms</h4><p>${t.labor}</p></div></div>${refs(t.refs,i>0)}${i?`<div class="table-wrap"><table><thead><tr><th>Fixed-scope labor saving</th>${D.scenarios.map(s=>`<th>${s.name}</th>`).join('')}</tr></thead><tbody><tr><td>Additional to 2026</td>${D.scenarios.map(s=>`<td>${pct(estimate(s.id,i).net)}</td>`).join('')}</tr></tbody><caption>Conditional A01 outputs; not published predictions. ${refs(t.refs,true)}</caption></table></div>`:''}</div></article>`).join('')}</div>`;}
function tasks(){const visible=D.tasks.filter(t=>(state.taskTag==='All'||t.tag===state.taskTag)&&(t.title+' '+t.items.join(' ')+' '+t.current).toLowerCase().includes(state.taskQuery.toLowerCase()));
return intro('THE WHOLE JOB · 14 CLUSTERS / 59 TASK EXAMPLES','What engineers<br><span class="accent">actually do.</span>','A synthesized building-structures workflow grounded in occupational profiles, a real employer role description and professional guidance. Engineer, BIM technician, specialist and fabricator duties vary by contract and firm.')+
`${refs(['S02','S03','S04','S13'])}<div class="notice">Weights are assumed team effort shares. They do not describe a typical engineer’s measured week. Adjust them in the <a href="#scenarios">scenario lab</a>. BIM lists structural design documentation; shop fabrication detailing may belong to a separate party. ${refs(['S03','S04'],true)}</div>
<div class="controls block"><label class="sr">Search tasks<input id="task-search" type="search" placeholder="Search e.g. Revit, RFI, seismic…" value="${esc(state.taskQuery)}"></label><label>Category<select id="task-tag">${['All','Engineering','BIM','Delivery','Field','Assurance'].map(v=>`<option ${v===state.taskTag?'selected':''}>${v}</option>`).join('')}</select></label><span class="table-note">${visible.length} of 14 clusters</span></div>
<div id="task-list">${visible.length?visible.map(t=>`<details class="card task"><summary><div><h3>${t.title}</h3><small>${t.tag} · ${t.items.length} task examples · assumed baseline weight ${t.weight}%</small></div></summary><div class="task-body"><div class="task-cols"><div><h4>Work in the cluster</h4><ul>${t.items.map(x=>`<li>${x}</li>`).join('')}</ul><h4>Current tools / use cases</h4><p>${t.current}</p></div><div><h4>Projected direction · author inference</h4><p>${t.future}</p><h4>Human decision or accountability</h4><p>${t.human}</p><div class="table-wrap"><table><thead><tr><th>Horizon</th><th>Gross potential input pᵢ,t</th></tr></thead><tbody>${t.potential.map((v,i)=>`<tr><td>${D.horizons[i+1]}</td><td>${v}%</td></tr>`).join('')}</tbody><caption>Assumed within-cluster removable share before capability, adoption and additional overhead. Not net project savings. ${refs(t.refs,true)}</caption></table></div></div></div>${refs(t.refs,true)}</div></details>`).join(''):'<p class="empty">No matching clusters. Try another term or category.</p>'}</div>`;}
const evidenceItems=[
 ['S01','+6%','Broad job demand baseline','BLS projects civil-engineer employment growth over 2025–2035; it does not isolate structural engineers or future AI displacement.'],
 ['S05','45% / 34%','No implementation / pilots','RICS finds low construction-project deployment in its Q1 2025 survey. This is broader than design-office use.'],
 ['S06','74%','Architecture practice adoption','Any use in some projects. The related RIBA series reports 41% in 2024 and 59% in 2025 [S07].'],
 ['S20','82% reported','Controlled structural iteration','Arup reports a large saving with engineer review retained. Its stated 2.5→0.5-day endpoints imply 80%; do not apply this to an entire job.'],
 ['S08','82–86%','Statics exam score','Tailored model score in the public abstract; remaining errors include tension/compression identification. Not code-compliant project delivery.'],
 ['S09','25.64 → 50.00%','Structural-design benchmark range','Selected Table 2 model results: GPT-4o 25.64%, o3-high 41.03%, Gemini-2.5-Pro 50.00%. Different models, not longitudinal improvement.'],
 ['S10','32%','BIM agent success','Architectural modeling tasks through GUI use. A promising prototype whose success metric is not structural model accuracy.'],
 ['S11','+21.0%','BIM evaluation-score change','A domain-tuned model improves G-Eval over its base model. This is not a labor-time saving.'],
 ['S14','43%','Digital processes in safety reports','IStructE review of over 900 CROSS reports. A selected reporting sample; not the failure rate of engineering or AI.'],
 ['S16','+15%','Observed support productivity','Published QJE study: 5,172 customer-support agents, issues resolved per hour. Useful causal context, different work.'],
 ['S17','+19% time','Experienced developers slowed','Randomized experiment: 16 developers, 246 real tasks using early-2025 tools. Benchmark capability can differ from practical utility.'],
 ['S15','Human responsibility','Professional boundary','NCEES PS 6.10 calls for independent validation and continued licensed responsibility. It is a policy position, not a promise about future law.']
];
function evidence(){return intro('MEASUREMENTS, DEPLOYMENTS AND COUNTEREVIDENCE','Useful signals.<br><span class="accent">Different denominators.</span>','An adoption rate, exam score, task pass rate and time saving measure different things. These cards are deliberately not combined into a single “AI capability” score.')+
`<div class="grid three">${evidenceItems.map(([id,metric,title,note])=>{let s=source(id);return `<article class="card evidence-card">${badge(s.kind,s.kind.includes('policy')?'inference':'observed')}<div class="metric">${metric}</div><h3>${title}</h3><p>${note}</p><p class="limitation"><strong>Scope / limitation:</strong> ${s.limitation}</p>${refs(id==='S06'?[id,'S07']:[id])}</article>`;}).join('')}</div>
<div class="grid two block"><div class="card"><h3>Deployed optimization and emerging platforms</h3><p>Arup/YJK describes bounded RC/steel and piled-foundation optimization. Arup’s September 2026 ArchSD announcement describes new agentic long-span and foundation commissions. The latter is a development announcement, not independent proof of finished autonomous delivery.</p>${refs(['S20','S21'])}</div><div class="card"><h3>BIM integration has a foundation</h3><p>Official Autodesk material documents selected authoring assistance in Revit 2027. buildingSMART’s IFC supports vendor-neutral data exchange. Neither establishes that a structurally correct model can be produced autonomously.</p>${refs(['S12','S18'])}</div></div>
<div class="notice"><strong>Research arithmetic check:</strong> S20 reports ~82% less iteration time; 1 − 0.5/2.5 = 80%. It reports ~88% fewer over-limit components; 1 − 6/64 = 90.625%. Reported figures and rounded endpoints disagree. This dashboard preserves both rather than inventing a reconciliation. ${refs(['S20'])}</div>`;}
function lab(){let r=estimate(state.scenario,state.horizon),sc=D.scenarios.find(x=>x.id===state.scenario),year=D.horizons[state.horizon],years=year-2026,index=Forecast.laborIndex(r.net,years,state.growth/100,years?state.newWork/100:0),be=Forecast.breakEven(r.net,years,years?state.newWork/100:0);
return intro('EXPLORE CONDITIONAL OUTCOMES','Hours saved ≠<br><span class="accent">jobs eliminated.</span>','Choose a technology scenario, change the task mix and test demand growth. The results are an illustrative accounting model, not a statistical employment forecast.')+
`<div class="grid three">${D.scenarios.map(s=>`<article class="card scenario-card ${s.id===sc.id?'selected':''}"><span class="tag">${s.id==='central'?'Central working hypothesis':s.id==='slow'?'Slower path':'Faster path'}</span><h3 style="margin-top:14px">${s.name}</h3><p>${s.story}</p><p><strong>Watch for:</strong> ${s.trigger}</p>${refs(s.refs,true)}<button class="choose-scenario" data-scenario="${s.id}" aria-pressed="${s.id===sc.id}">Explore this scenario</button></article>`).join('')}</div>
<div class="card block"><div class="section-head"><div><h2>Set the horizon and market</h2><p>All inputs below are assumptions. New work is additive labor per project relative to the 2026 baseline.</p></div>${badge('What-if model','forecast')}</div><div class="controls"><label>Horizon<select id="horizon">${D.horizons.map((y,i)=>`<option value="${i}" ${i===state.horizon?'selected':''}>${y}${i?' / +'+(y-2026)+' years':' / today'}</option>`).join('')}</select></label><button id="reset-lab">Reset assumptions</button><button id="export-lab">Export current assumptions</button></div>
<div class="grid two"><div class="range-field"><label for="growth">Annual engineering-service output growth <output>${state.growth.toFixed(1)}%</output></label><input id="growth" type="range" min="-2" max="5" step="0.1" value="${state.growth}"></div><div class="range-field"><label for="new-work">New scope / assurance labor <output>${state.newWork}% of baseline hours</output></label><input id="new-work" type="range" min="0" max="30" step="1" value="${state.newWork}"></div></div>
<div class="grid four model-kpis"><div class="card"><div class="eyebrow">NET HOURS REMOVED</div><div class="metric">${pct(r.net)}</div><div class="stat-note">Fixed scope, versus 2026</div></div><div class="card"><div class="eyebrow">HOURS REMAINING</div><div class="metric">${(100*r.remaining).toFixed(1)}</div><div class="stat-note">Per 100 baseline hours</div></div><div class="card"><div class="eyebrow">LABOR DEMAND INDEX</div><div class="metric">${index.toFixed(0)}</div><div class="stat-note">2026 = 100; includes demand + new work</div></div><div class="card"><div class="eyebrow">BREAK-EVEN GROWTH</div><div class="metric">${years?pct(be):'—'}</div><div class="stat-note">Annual output growth for index 100</div></div></div>${refs(['S01','S05','S15','S19','S24'],true)}</div>
<div class="grid two block"><div class="card"><h3>Hours per 100 baseline hours · ${year}</h3><figure>${hourChart(r)}<figcaption>Figure 2. Gross saving ${pct(r.gross)}, minus ${pct(r.overhead)} added review/integration/rework = ${pct(r.net)} net. Baseline already includes routine review. Only added overhead is subtracted. ${refs(['S13','S15','S17'],true)}</figcaption></figure></div>
<div class="card"><h3>Demand sensitivity · ${year}</h3><div class="table-wrap"><table><thead><tr><th>Output growth / year</th><th>Labor index</th><th>Change vs. 2026</th></tr></thead><tbody>${[0,1.5,3].map(g=>{let j=Forecast.laborIndex(r.net,years,g/100,years?state.newWork/100:0);return `<tr><td>${g.toFixed(1)}%</td><td>${j.toFixed(0)}</td><td>${(j-100>=0?'+':'')+(j-100).toFixed(0)}%</td></tr>`;}).join('')}</tbody><caption>Same ${sc.name.toLowerCase()} case; ${years?state.newWork:0}% new labor per baseline project. Index describes modeled total labor need, not vacancies or actual headcount. ${refs(['S01','S19','S24'],true)}</caption></table></div></div></div>
<div class="card block"><h2>Inspect and change the whole task mix</h2><p class="subtle">Raw weights are normalized to 100%. Changing them updates all forecast charts and tables. Zero weights remove a cluster; if all are zero, the baseline is used. All values are editable assumptions.</p><div class="controls"><label>Workload preset<select id="profile"><option value="custom">Current / custom mix</option value="balanced">Balanced design team</option><option value="bim">BIM production emphasis</option><option value="field">Existing-building / field emphasis</option></select></label></div><div class="weight-total">${Object.keys(state.weights).length?'Custom':'Baseline'} weights · ${D.tasks.reduce((v,t)=>v+(state.weights[t.id]??t.weight),0)} raw points</div><div class="table-wrap"><table><thead><tr><th>Cluster</th><th>Raw weight</th><th>Normalized share</th><th>Gross within-task saving</th><th>Project contribution</th><th>Context</th></tr></thead><tbody>${D.tasks.map((t,i)=>{let b=r.byTask[i];return `<tr><td><strong>${t.title}</strong><br><span class="tag">${t.tag}</span></td><td><input class="task-weight" data-task="${t.id}" aria-label="Weight for ${esc(t.title)}" type="number" min="0" max="100" step="1" value="${state.weights[t.id]??t.weight}" style="width:72px"></td><td>${pct(b.weight)}</td><td>${pct(b.removable)}</td><td>${pct(b.weight*b.removable)}</td><td>${refs(t.refs,true)}</td></tr>`;}).join('')}</tbody><caption>Table 3. A01 calculation inputs and gross category contributions. Contributions sum to gross project saving; subtract the ${pct(r.overhead)} overall additional overhead once. No category score is a research-measured automation rate. ${refs(['S02','S03','S13'],true)}</caption></table></div></div>
<div class="notice"><strong>Interpret the output carefully.</strong> An index below 100 means less total labor required under these assumptions. It does not say which employees lose jobs. New services, changing fees, wages, task mix and capital are simplified or omitted. The numbers are sensitivities, not a forecast endorsed by the cited institutions.</div>`;}
function hourChart(r){const rows=[['Remaining original work',1-r.gross,'var(--muted)'],['Additional checking / rework',r.overhead,'var(--forecast)'],['Net hours released',r.net,'var(--accent)']];return `<svg class="chart" viewBox="0 0 470 185" role="img" aria-label="Hours per 100 baseline hours: ${rows.map(([l,v])=>l+' '+(v*100).toFixed(1)).join('; ')}">${rows.map(([label,v,color],i)=>`<text x="0" y="${20+i*60}" fill="var(--muted)" font-size="11">${label}</text><rect x="0" y="${30+i*60}" width="400" height="8" rx="4" fill="var(--line)"/><rect x="0" y="${30+i*60}" width="${Math.max(0,v)*400}" height="8" rx="4" fill="${color}"/><text x="465" y="${39+i*60}" text-anchor="end" font-size="13" fill="var(--ink)">${(v*100).toFixed(1)}</text>`).join('')}</svg>`;}
const careers=[
 ['01','Routine digital production','Higher exposure · author inference','Repetitive calculation setup, sheet/view management, tagging, schedules and document comparison are natural first targets. A role concentrated here is more vulnerable than one with broad design ownership.',['S03','S10','S12','S20']],
 ['02','The early-career pipeline','Training pressure · author inference','If routine tasks shrink, firms must deliberately preserve hand checks, model-building practice, detailing and site exposure. Engineers need competence to review an AI result, not just to prompt it.',['S03','S08','S13','S15']],
 ['03','Experienced technical specialists','Relative resilience · conditional','Complex behavior, rehabilitation, forensic work, uncertainty and constructability remain valuable. This is a relative advantage, not immunity: stronger agents could eventually automate much of this work too.',['S03','S09','S13','S15']],
 ['04','BIM professionals','Role shift · author inference','Pure repetitive authoring becomes less scarce. Model architecture, standards, parameters, coordination, analytical consistency and reliable automation become more important.',['S03','S10','S11','S12','S18']],
 ['05','Principals and engineers of record','Accountability is not a hiring guarantee','Current policy preserves responsibility. It does not preserve today’s team size: one qualified lead could oversee more output, and checking workloads may become the capacity bottleneck.',['S03','S13','S15','S20']],
 ['06','Firm economics','More output, fee pressure, uneven gains','If clients demand the same deliverables for less, productivity can compress revenue. If firms sell broader assessment and design services, output can expand. Neither outcome follows automatically from tool capability.',['S01','S05','S19','S24']]
];
function career(){return intro('SKILLS, TRAINING AND THE BUSINESS OF DESIGN','What becomes<br><span class="accent">more valuable?</span>','My prediction is a shift in the scarce skill: from producing routine output to deciding what should be produced, proving it is valid and resolving real-world uncertainty. That shift can be painful even if the profession survives.')+`${refs(['S03','S13','S15','S20'],true)}<div class="grid two career-grid block">${careers.map(([n,title,label,text,ids])=>`<article class="card"><div class="stage-number">${n} / ${label.toUpperCase()}</div><h3>${title}</h3><p>${text}</p>${refs(ids,true)}</article>`).join('')}</div>
<div class="card block"><h2>A practical preparation path</h2><div class="grid two"><div><div class="pillar"><h3>Master mechanics and failure behavior</h3><p>Practice equilibrium, load paths, stability, serviceability, detailing and independent checks. These support competent review as production changes.</p>${refs(['S03','S08','S15'])}</div><div class="pillar"><h3>Learn the data path</h3><p>Understand BIM parameters, physical versus analytical models, APIs, Python and IFC. Distinguish model completeness from numerical solver success.</p>${refs(['S03','S12','S18'])}</div></div><div><div class="pillar"><h3>Automate one bounded workflow well</h3><p>Choose a repetitive workflow, establish expected outputs and record total time including setup, correction and review. Scale based on measured outcomes.</p>${refs(['S13','S15','S17'],true)}</div><div class="pillar"><h3>Build field and client judgment</h3><p>Seek construction administration, existing-condition investigation and interdisciplinary negotiation. These broaden your value beyond routine production.</p>${refs(['S02','S03','S04'],true)}</div></div></div></div>
<div class="notice"><strong>Watch five leading indicators:</strong> audited hours per complete project; defect/rework rates; junior hiring and training; fee per project versus output; and acceptance of verifiable automated delivery by clients, insurers and authorities. These are proposed monitoring metrics, not measured trends. ${refs(['S05','S13','S15','S17'],true)}</div>`;}
function methods(){return intro('AUDITABLE MODEL · NO HIDDEN FORECAST ENGINE','Assumptions<br><span class="accent">in plain sight.</span>','Research informs the mechanism. It does not supply a measured automation percentage for the complete structural-engineering role. The following model makes the missing inputs visible.')+
`<article class="card" id="A01">${badge('A01 · author assumptions','forecast')}<h2 style="margin-top:18px">Task-weighted net labor saving</h2><p>${D.method.description}</p><div class="formula"><math xmlns="http://www.w3.org/1998/Math/MathML" aria-label="S equals sum of w i times minimum of 0.98 and p i t times c s t times a s t, minus h s t"><mi>S</mi><mo>=</mo><munder><mo>∑</mo><mi>i</mi></munder><msub><mi>w</mi><mi>i</mi></msub><mo>×</mo><mi>min</mi><mo>(</mo><mn>0.98</mn><mo>,</mo><msub><mi>p</mi><mrow><mi>i</mi><mo>,</mo><mi>t</mi></mrow></msub><mo>×</mo><msub><mi>c</mi><mrow><mi>s</mi><mo>,</mo><mi>t</mi></mrow></msub><mo>)</mo><mo>×</mo><msub><mi>a</mi><mrow><mi>s</mi><mo>,</mo><mi>t</mi></mrow></msub><mo>−</mo><msub><mi>h</mi><mrow><mi>s</mi><mo>,</mo><mi>t</mi></mrow></msub></math></div><dl class="term-list">${Object.entries(D.method.terms).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}</dl><p class="subtle">Subscripts: i = task cluster; t = horizon; s = scenario. Inputs use fractions (e.g. 0.20 for 20%). The 0.98 within-category cap is an arbitrary modeling safeguard, not a physical or regulatory limit. Existing review is in the baseline; h adds only new overhead. Today’s value is zero additional savings by definition.</p>${refs(D.method.refs,true)}</article>
<div class="card block"><h2>All scenario multipliers and overheads</h2><div class="table-wrap"><table><thead><tr><th>Scenario</th><th>Year</th><th>Capability c</th><th>Realization a</th><th>Added overhead h</th></tr></thead><tbody>${D.scenarios.map(s=>D.horizons.slice(1).map((y,j)=>{let i=j+1;return `<tr><td>${s.name}</td><td>${y}</td><td>${s.capability[i].toFixed(2)}</td><td>${s.adoption[i].toFixed(2)}</td><td>${pct(s.overhead[i])}</td></tr>`;}).join('')).join('')}</tbody><caption>Table 4. A01 author inputs. The central multipliers decrease at long horizons to discount extrapolated category potentials. Constrained adoption retains a persistent capability/integration discount; faster substitution realizes more of the digital workload. Exact values are judgmental, not fitted. Per-task potentials are listed in the task atlas and JSON dataset. ${refs(['S05','S09','S10','S13','S15','S20'],true)}</caption></table></div></div>
<div class="card block"><h2>From per-project hours to total labor demand</h2><div class="formula"><math xmlns="http://www.w3.org/1998/Math/MathML" aria-label="J divided by J zero equals one plus g to the T power times one minus S plus n"><mfrac><mi>J</mi><msub><mi>J</mi><mn>0</mn></msub></mfrac><mo>=</mo><msup><mrow><mo>(</mo><mn>1</mn><mo>+</mo><mi>g</mi><mo>)</mo></mrow><mi>T</mi></msup><mo>×</mo><mo>(</mo><mn>1</mn><mo>−</mo><mi>S</mi><mo>+</mo><mi>n</mi><mo>)</mo></math></div><dl class="term-list">${Object.entries(D.method.jobTerms).map(([k,v])=>`<dt>${k}</dt><dd>${v}</dd>`).join('')}<dt>J/J₀</dt><dd>Modeled labor requirement relative to baseline; the displayed index is 100 × this ratio.</dd></dl><p class="subtle">This is an accounting identity under stated constant-mix assumptions, not an econometric employment model. At T = 0, new work is set to zero. Break-even growth = (1 / (1 − S + n))^(1/T) − 1. Default g = 2% and n = 10% are illustrative; BLS growth is not used to calibrate them.</p>${refs(['S01','S19','S24'],true)}</div>
<div class="grid two block"><div class="card"><h3>Limits and alternative paths</h3><ul class="check-list">${D.method.limits.map(x=>`<li>${x}</li>`).join('')}</ul>${refs(['S05','S09','S14','S15','S17'],true)}</div><div class="card"><h3>Research protocol</h3><p>Selected online review conducted on 30 September 2026, focused on primary occupational data, employer duties, structural/BIM studies, professional policy, documented deployments and real-world productivity research. This is a curated review, not a systematic meta-analysis.</p><p>References state what was read: full accessible pages or tables where available, abstracts for specified papers and indexed official excerpts when retrieval failed. Company results remain company-reported. No source published after the cut-off is intentionally used.</p><h3>Why plain HTML / CSS / JavaScript?</h3><p>A finite research dashboard needs no server, framework runtime or build dependency. Native JavaScript supports charts, filters and scenario calculations; static files work locally and on GitHub Pages. React adds unnecessary lifecycle/build overhead; Jekyll adds a generator without helping the model; Astro is useful for a larger content site but not required here.</p>${refs(['S23'])}<p class="subtle">Architecture choice is author judgment. Research dates are frozen; this dashboard does not automatically update when models, software or laws change.</p></div></div>`;}
function references(){const list=D.sources.filter(s=>(state.sourceKind==='All'||s.kind===state.sourceKind)&&(s.id+' '+s.title+' '+s.author+' '+s.finding).toLowerCase().includes(state.sourceQuery.toLowerCase()));return intro('24 SOURCES · LINKED AT THE POINT OF USE','Read the source.<br><span class="accent">Check the boundary.</span>','Every citation opens its entry here. Each entry identifies the claim used, scope, document location and limits. A01 refers to the author’s scenario assumptions; sources support context, not invented precision.')+`<div class="controls block"><label>Find a source<input id="source-search" type="search" placeholder="Search title, author, claim or ID…" value="${esc(state.sourceQuery)}"></label><label>Evidence type<select id="source-kind">${['All',...new Set(D.sources.map(s=>s.kind))].map(k=>`<option ${k===state.sourceKind?'selected':''}>${k}</option>`).join('')}</select></label><span class="table-note">${list.length} entries</span></div>${list.map(s=>`<article class="card source-card" id="ref-${s.id}"><div class="source-top"><div><span class="source-id">[${s.id}]</span> <span class="tag">${s.kind}</span><h3>${s.title}</h3></div><a class="source-open" href="${s.url}" target="_blank" rel="noopener noreferrer">Open original ↗</a></div><div class="source-meta">${s.author} · ${s.date} · Accessed ${s.accessed}</div><p><b>Finding used:</b> ${s.finding}</p><p><b>Scope:</b> ${s.scope}</p><p><b>Limit:</b> ${s.limitation}</p><p><b>Location:</b> ${s.locator}</p>${s.id==='S12'?'<p><b>Supplementary official entries:</b> <a href="https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/How-to-enable-Autodesk-Assistant-in-Revit.html" target="_blank" rel="noopener">Availability</a> · <a href="https://www.autodesk.com/support/technical/article/caas/sfdcarticles/sfdcarticles/What-AI-features-are-available-in-Revit.html" target="_blank" rel="noopener">AI features</a>. Indexed official excerpts read; support page returned no extractable body.</p>':''}</article>`).join('')}${!list.length?'<p class="empty">No references match those filters.</p>':''}`;}
const views={overview,timeline,tasks,evidence,scenarios:lab,career,methods,references};
function render(keepScroll=false){let [view,id]=(location.hash.slice(1)||'overview').split('/');if(!views[view])view='overview';if(view==='references'&&id){state.sourceQuery='';state.sourceKind='All';}const before=scrollY;$('#content').innerHTML=views[view]();document.querySelectorAll('nav a').forEach(a=>{let active=a.hash==='#'+view;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});bind(view);if(keepScroll)scrollTo(0,before);else scrollTo(0,0);if(id&&view==='references'){let el=document.getElementById('ref-'+id);if(el){el.classList.add('highlight');el.scrollIntoView({behavior:'smooth',block:'start'});}}document.title=({overview:'Overview',timeline:'30-Year Timeline',tasks:'Task Atlas + BIM',evidence:'Evidence',scenarios:'Scenario Lab',career:'Career Implications',methods:'Methods',references:'References'}[view])+' — Structural Futures';}
function keepFocus(selector,fn){const el=$(selector),pos=el?.selectionStart;fn();const replacement=$(selector);if(replacement){replacement.focus({preventScroll:true});if(pos!=null&&replacement.setSelectionRange)replacement.setSelectionRange(pos,pos);}}
function bind(view){
 if(view==='tasks'){
 $('#task-search').addEventListener('input',e=>{state.taskQuery=e.target.value;keepFocus('#task-search',()=>render(true));});
 $('#task-tag').addEventListener('change',e=>{state.taskTag=e.target.value;render(true);});
 }
 if(view==='references'){
 $('#source-search').addEventListener('input',e=>{state.sourceQuery=e.target.value;const hadId=location.hash.includes('/');if(hadId)history.replaceState(null,'','#references');keepFocus('#source-search',()=>render(true));});
 $('#source-kind').addEventListener('change',e=>{state.sourceKind=e.target.value;if(location.hash.includes('/'))history.replaceState(null,'','#references');render(true);});
 }
 if(view==='scenarios'){
 document.querySelectorAll('.choose-scenario').forEach(b=>b.addEventListener('click',()=>{state.scenario=b.dataset.scenario;render(true);}));
 $('#horizon').addEventListener('change',e=>{state.horizon=Number(e.target.value);render(true);});
 for(const [id,key] of [['growth','growth'],['new-work','newWork']]){const slider=$('#'+id);slider.addEventListener('input',e=>{state[key]=Number(e.target.value);const out=e.target.previousElementSibling.querySelector('output');out.textContent=id==='growth'?state.growth.toFixed(1)+'%':state.newWork+'% of baseline hours';});slider.addEventListener('change',()=>keepFocus('#'+id,()=>render(true)));}
 document.querySelectorAll('.task-weight').forEach(el=>el.addEventListener('change',()=>{state.weights[el.dataset.task]=Math.min(100,Math.max(0,Number(el.value)||0));render(true);}));
 $('#reset-lab').addEventListener('click',()=>{Object.assign(state,{scenario:'central',horizon:2,growth:2,newWork:10,weights:{}});render(true);});
 $('#profile').addEventListener('change',e=>{const presets={balanced:D.tasks.map(t=>t.weight),bim:[3,5,5,8,7,30,17,8,5,4,2,2,2,2],field:[8,5,7,8,10,4,5,8,10,12,15,3,2,3]};let arr=presets[e.target.value];if(arr)state.weights=Object.fromEntries(D.tasks.map((t,i)=>[t.id,arr[i]]));render(true);});
 $('#export-lab').addEventListener('click',()=>{const output={asOf:D.asOf,method:'A01',scenario:state.scenario,year:D.horizons[state.horizon],annualOutputGrowth:state.growth/100,newWorkFraction:state.newWork/100,taskWeights:D.tasks.map(t=>({id:t.id,weight:state.weights[t.id]??t.weight})),result:estimate(state.scenario,state.horizon),notice:'Author conditional assumptions. Not a measured forecast or job-loss prediction.'};const blob=new Blob([JSON.stringify(output,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='structural-futures-assumptions.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 }
}
$('#theme').addEventListener('click',()=>{document.body.classList.toggle('light');const light=document.body.classList.contains('light');$('#theme').setAttribute('aria-label','Switch to '+(light?'dark':'light')+' theme');try{localStorage.setItem('structural-futures-theme',light?'light':'dark');}catch{}});
try{if(localStorage.getItem('structural-futures-theme')==='light'){document.body.classList.add('light');$('#theme').setAttribute('aria-label','Switch to dark theme');}}catch{}
window.addEventListener('hashchange',()=>render());render();
